### ISSUE TITLE
Awaiting resolution: favicons and apple-touch-icons

### ISSUE THREAD

**Issue by annapowellsmith** [cyclestreets/mobileweb2011#14]
1. We have two favicons - one at /favicon.ico and images/favicon.ico - let's just have one :)
2. Should we add a bunch of apple-touch-icons as referenced in the headers? and what should these be?

**Comment by mvl22** [comment]
Should be at /favicon.ico only.

Based on
http://developer.apple.com/library/safari/#documentation/appleapplications/reference/safariwebcontent/configuringwebapplications/configuringwebapplications.html
looks like we just want to use
apple-touch-icon.png
which will add the apple shine automatically :)

So I think the action here is to remove all the headers that are there and just use:

<link rel="apple-touch-icon" href="/apple-touch-icon.png" />
and make a file apple-touch-icon.png that's the same as favicon.ico

**Comment by annapowellsmith** [comment]
OK, I've 
- removed the other favicon
- updated the favicon references
- removed surplus Apple tags
- made a new apple-touch-icon.png icon (based on bottom layer of favicon resized to 57x57)
- made a new apple-touch-startup-image.png (based on iOS repo's splash screen)
- updated header tags in all files.
