### ISSUE TITLE
Add the splash image to the very end of the front page for Facebook sharing

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/mobileweb2011#18]
Share http://m.cyclestreets.net/ results in a poor link-extract because there's basically no images, just a pile of divs etc.

A simple solution would be to add the splash image to the very end of the front page so that users don't routinely see it, but so that Facebook and other sharing solutions pick it up.

Perhaps there is a better way to do this.

**Comment by annapowellsmith** [comment]
<link rel="image_src" ... /> in the head seems to be the way to go. I've implemented this, and added some special Facebook preview images too.
