### ISSUE TITLE
Opera can't cope with "pointer-events: none"

### ISSUE THREAD

**Issue by annapowellsmith** [cyclestreets/mobileweb2011#2]
... which makes the journey map undraggable, as the crosshairs create a large dead spot in the centre of the screen. 

Suggested workaround: check for Opera with user-agent, and set the height of the crosshairs to about 40px. Probably the best we can do.

**Comment by mvl22** [comment]
Workaround sounds sensible.

**Comment by annapowellsmith** [comment]
Have pushed this.
