### ISSUE TITLE
iPad/iPod should be treated same as iPhone

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/mobileweb2011#22]
The native iOS app works the same on iPhone, iPod and iPad though is not optimised for the latter.

Therefore this commit
https://github.com/cyclestreets/mobileweb/commit/2d0e29e59b579494e85df405e1a2da7c3877b87a
should be changed so that all three devices have the same behaviour, namely to advertise the native app.

**Comment by annapowellsmith** [comment]
Fixed in https://github.com/cyclestreets/mobileweb/commit/8ce7a79c251c86e54319939f8206d156ee2bd939
