### ISSUE TITLE
Display bug for Android Firefox beta

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/mobileweb2011#23]
Reported:
http://twitter.com/#!/jugglerchris/status/111365421596282881

though it is beta.

Leave this bug report open till we know it works, or that Android Firefox non-beta is fine.

**Comment by annapowellsmith** [comment]
Was able to debug in Firefox desktop - have pushed a fix for this.

**Comment by mvl22** [comment]
Thanks; will notify the reporter.

https://github.com/cyclestreets/mobileweb/commit/feb7b656a5568c70fcb8157926fcdb0b37076488
is the commit.
