### ISSUE TITLE
Attribution missing

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/mobileweb2011#28]
Very important: the map is missing attribution in the bottom-right corner.

Basically should use the same strings as: http://www.cyclestreets.net/cyclestreets.js

**Comment by annapowellsmith** [comment]
I raised this before - is this absolutely critical? Our screen space is _so_ limited that we really need to minimise clutter. 

Plus, it'll be another processor-intensive, potentially browser-variable bit of code to position the element using jQuery each time the page resizes.  

The OSM terms say 'This credit needs to appear in a place "reasonable to the medium or means you are utilising": http://wiki.openstreetmap.org/wiki/Legal_FAQ#I_would_like_to_use_OpenStreetMap_maps._How_should_I_credit_you.3F

I'd argue that it's reasonable for the credit to appear on the About page...

**Comment by mvl22** [comment]
Agreed; that's fine.

**Comment by annapowellsmith** [comment]
I've added an extra sentence on the About page so it conforms to the format requested by OSM: https://github.com/cyclestreets/mobileweb/commit/4660f9613c9e172346ff4983b7a64b09fa278cdb
