### ISSUE TITLE
Photo date shown as '0'

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/mobileweb2011#29]
http://m.cyclestreets.net/location/#9056
shows "0/8/2006" for the date, but the main site version doesn't have this problem:

http://www.cyclestreets.net/location/9056/
"Date:  2.57pm, 10th September, 2006"

**Comment by annapowellsmith** [comment]
Hm! 

The API call is http://www.cyclestreets.net/api/photo.json?callback=photo&key=68f786d958d1dbfb&id=9056&_=1315995884908

which has datetime: "1157896646"

Debugging this now...

**Comment by annapowellsmith** [comment]
My bad - I had confused JavaScript's getDate() which returns the day of the month (from 1-31) with getDay(), which returns the day of the week (from 0-6). Just pushed a fix: https://github.com/cyclestreets/mobileweb/commit/2e645dbfc5716e9b4a2a3d7352712718eff84f3a

**Comment by si-the-pie** [comment]
Shaun reports: "Photo with the month in the date being zero"

http://m.cyclestreets.net/location/#47326

**Comment by smsm1** [comment]
Yup that change seems to have fixed it. (I can't close issues in this repo).

**Comment by si-the-pie** [comment]
What about the leading zero? Though...

Partially fixed: http://m.cyclestreets.net/location/#47326 now has
22/1/2013, so how do we get the leading zero too?

On 23 January 2013 23:21, Shaun McDonald notifications@github.com wrote:

> Yup that change seems to have fixed it. (I can't close issues in this
> repo).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cyclestreets/mobileweb/issues/29#issuecomment-12628546.

## 

Simon

# 

Simon Nuttall
100 Thoday Street
Cambridge
CB1 3AX
01223 500902
+44 1223 500902

**Comment by smsm1** [comment]
https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/Date

You need to write a pad function to add the leading 0 as per the example given towards the bottom of the above page.

**Comment by si-the-pie** [comment]
Fixed by https://github.com/cyclestreets/mobileweb/commit/37bc201d3061fd27b8a932e50ce4e4632fb3c43b

**Comment by mvl22** [comment]
This has been replaced now with a human-readable datetime, using datetime=friendly which is available in the V2 API.

See:
https://github.com/cyclestreets/mobileweb/commit/22c922d5f00dbafc39deb4f713c4fbf7e021b638
