### ISSUE TITLE
Dates in "saved routes" showing as NaN in Android browser

### ISSUE THREAD

**Issue by annapowellsmith** [cyclestreets/mobileweb2011#36]
Observed in Android browser. But working fine in Chrome.

Something to do with different browsers presenting the JavaScript Date object differently? Or simple caching? Or localstorage differences?

Investigate.

**Comment by si-the-pie** [comment]
Confirmed this is still broken on Android htc Wildfire.

Works fine on Blackberry Playbook.

**Comment by si-the-pie** [comment]
Some posts I've read suggest changing `-` to `/` in the date.

This one:
http://stackoverflow.com/questions/3046459/ie-date-parse-method-returns-nan-for-date-with-time-string
suggests using `.replace(/\-/ig, '/').split('.')[0]`.

**Comment by si-the-pie** [comment]
Fixed by...

https://github.com/cyclestreets/mobileweb/commit/f7d19bc200887fc5f855b0e46500b921f427faf1
