### ISSUE TITLE
Multiple waypoints

### ISSUE THREAD

**Issue by si-the-pie** [cyclestreets/mobileweb2011#44]
It should be fairly simple to extend the interface so that multiple waypoints can be set before planning a route.

It would work in a very similar way to the android version, like a stack:

The first tap sets the start.

Successive taps add new waypoints giving the option of either planning the route or adding a new point.

Remove simply removes the last waypoint.

The API is currently limited to 50 such points.

**Comment by mvl22** [comment]
> It would work in a very similar way to the android version, like a stack:

Yes, the Android version should be the model. Do it exactly like that 
please!

**Comment by si-the-pie** [comment]
This was implemented in August 2012.
