### ISSUE TITLE
Awaiting resolution: Add link to desktop site

### ISSUE THREAD

**Issue by annapowellsmith** [cyclestreets/mobileweb2011#6]
Add non-redirecting link to desktop site - in footer perhaps. 

Make sure link to donate page does not redirect.

**Comment by annapowellsmith** [comment]
have added placeholder link, waiting for MLS to confirm precise URL structure.

**Comment by mvl22** [comment]
Can we just use
http://www.cyclestreets.net/

but set a cookie for cyclestreets.net of name
redirecttomobilesite = no
?

Then I can add into the sever-side script to look for such a cookie and redirect if none found?

**Comment by mvl22** [comment]
Actually, maybe this is best to do at our end after all. Will sort out the redirection code shortly and let you know the URL.
