### ISSUE TITLE
Crosshair moves slightly upon first load

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/mobileweb2011#8]
http://ipadpeek.com/
shows a problem that I've also found consistently on my iPhone.

On first load, shortly after the crosshair appears, it then moves about 5px or so to the right.

It then feels instinctively (though I've not measured it) like it's then not quite centred!

**Comment by annapowellsmith** [comment]
have just pushed a fix... browsers seem to vary slightly in the way they calculate width so I was adding 3px to compensate for slight off-centre look on some. have set it back to 'true' width so any error is really down to the browser!
